# Generated by Django 2.0.2 on 2018-02-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('facilitatorid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participantid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshopid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('occ_no', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('man_no_part', models.BigIntegerField(max_length=1000)),
                ('num_of_facil', models.BigIntegerField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='workshopid',
            field=models.ForeignKey(on_delete=None, to='workshopic.Workshop'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='workshopid',
            field=models.ForeignKey(on_delete=None, to='workshopic.Workshop'),
        ),
    ]
