# Generated by Django 2.0.2 on 2018-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='man_no_part',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='num_of_facil',
            field=models.BigIntegerField(),
        ),
    ]
